/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Variant({
  'preparedMeals' : IDL.Null,
  'other' : IDL.Null,
  'bakery' : IDL.Null,
  'meatFish' : IDL.Null,
  'fruitsVegetables' : IDL.Null,
  'frozen' : IDL.Null,
  'beverages' : IDL.Null,
  'dairy' : IDL.Null,
  'pantry' : IDL.Null,
});
export const PostId = IDL.Nat;
export const PickupStatus = IDL.Variant({
  'booked' : IDL.Null,
  'available' : IDL.Null,
  'pickedUp' : IDL.Null,
  'delivered' : IDL.Null,
});
export const FoodDonationPost = IDL.Record({
  'id' : PostId,
  'title' : IDL.Text,
  'expiryDate' : IDL.Text,
  'createdAt' : IDL.Int,
  'recipientContact' : IDL.Opt(IDL.Text),
  'accessCode' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'state' : IDL.Text,
  'ngoId' : IDL.Opt(IDL.Principal),
  'pickupTime' : IDL.Text,
  'quantity' : IDL.Nat,
  'category' : Category,
  'pickupStatus' : PickupStatus,
  'image' : IDL.Text,
  'recipientName' : IDL.Opt(IDL.Text),
  'donor' : IDL.Principal,
  'location' : IDL.Text,
  'recipientId' : IDL.Opt(IDL.Principal),
  'foodType' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const TrackingStep = IDL.Record({
  'status' : IDL.Text,
  'title' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPost' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Category,
        IDL.Text,
        IDL.Opt(IDL.Principal),
      ],
      [FoodDonationPost],
      [],
    ),
  'getAllPosts' : IDL.Func([], [IDL.Vec(FoodDonationPost)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentTracking' : IDL.Func([], [IDL.Vec(TrackingStep)], ['query']),
  'getHealthyListings' : IDL.Func([], [IDL.Vec(FoodDonationPost)], ['query']),
  'getMyPosts' : IDL.Func([], [IDL.Vec(FoodDonationPost)], ['query']),
  'getNearestListings' : IDL.Func([], [IDL.Vec(FoodDonationPost)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVegListings' : IDL.Func([], [IDL.Vec(FoodDonationPost)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Variant({
    'preparedMeals' : IDL.Null,
    'other' : IDL.Null,
    'bakery' : IDL.Null,
    'meatFish' : IDL.Null,
    'fruitsVegetables' : IDL.Null,
    'frozen' : IDL.Null,
    'beverages' : IDL.Null,
    'dairy' : IDL.Null,
    'pantry' : IDL.Null,
  });
  const PostId = IDL.Nat;
  const PickupStatus = IDL.Variant({
    'booked' : IDL.Null,
    'available' : IDL.Null,
    'pickedUp' : IDL.Null,
    'delivered' : IDL.Null,
  });
  const FoodDonationPost = IDL.Record({
    'id' : PostId,
    'title' : IDL.Text,
    'expiryDate' : IDL.Text,
    'createdAt' : IDL.Int,
    'recipientContact' : IDL.Opt(IDL.Text),
    'accessCode' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'state' : IDL.Text,
    'ngoId' : IDL.Opt(IDL.Principal),
    'pickupTime' : IDL.Text,
    'quantity' : IDL.Nat,
    'category' : Category,
    'pickupStatus' : PickupStatus,
    'image' : IDL.Text,
    'recipientName' : IDL.Opt(IDL.Text),
    'donor' : IDL.Principal,
    'location' : IDL.Text,
    'recipientId' : IDL.Opt(IDL.Principal),
    'foodType' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const TrackingStep = IDL.Record({
    'status' : IDL.Text,
    'title' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPost' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Category,
          IDL.Text,
          IDL.Opt(IDL.Principal),
        ],
        [FoodDonationPost],
        [],
      ),
    'getAllPosts' : IDL.Func([], [IDL.Vec(FoodDonationPost)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentTracking' : IDL.Func([], [IDL.Vec(TrackingStep)], ['query']),
    'getHealthyListings' : IDL.Func([], [IDL.Vec(FoodDonationPost)], ['query']),
    'getMyPosts' : IDL.Func([], [IDL.Vec(FoodDonationPost)], ['query']),
    'getNearestListings' : IDL.Func([], [IDL.Vec(FoodDonationPost)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVegListings' : IDL.Func([], [IDL.Vec(FoodDonationPost)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };